# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-22 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='tags',
            new_name='photo',
        ),
    ]
