# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-22 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='photos',
            name='dateuploaded',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
