# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20180922_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='services.Group'),
        ),
    ]
