# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-22 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('working', models.BooleanField(default=False)),
                ('group_url', models.URLField(null=True)),
                ('photo_url', models.URLField(null=True)),
                ('group_id', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
